[pyprland]
plugins = ["scratchpads"]

[scratchpads.volume]
animation = "fromTop"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
size = "50% 60%"

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm -e yazi"
class = "kitty-dropterm"
size = "75% 60%"
