k3s_token: ENC[AES256_GCM,data:RfFhvTLI,iv:1Xct7I2ZrcnRbQVNd25nUKDJzjrzkgboSpsH++aw8FA=,tag:4/Lk/KyWVhrRAoAqBrpi4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ff98yfdlxax5ymnlu9rdzermuyvg8jwq98z6h86tpj8ajlxw7upsq4k8a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUmR1UUZiNXkyM1ExVTdq
            dkVmdlZtaVZkOVVnTUdkOTZ0Uk1xU0YzVkdNCmZjUGxjQUlmQnlpZ0krM2p2TlNW
            Y3daZGVDL1JTa1I2NWJ0S0dDa3czRDgKLS0tIHZtUS9EbmN4SGUwRGc2c05FMm00
            ZVFSL3BWWkZaZTl1eTVIdlV1U0R6N1kK4qDoW3amWYg9XtaCCDTnIWbsEcfAhZq+
            JW1m/ZlmvCGDQuAdZkEebrPNxcUOjvwyqG0io2RUCXlBxd/6R9+3dA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-15T20:42:03Z"
    mac: ENC[AES256_GCM,data:R4fxA6jMoBR8NuDVbZmB+CJy+GbYDkvFsctV4JjwDZHHVcV9diw7iKI+hhTmHNK4SLfZ8XE5TBWODvBTm2DxgY5JCHUovxeXZiR/eGppuCZeoLuyc5udyaFUn5vLzZWMbXa49LsYlUmmqryserw+tpLgTCzZRbTwyCjOCyOHF7o=,iv:TFu0rnJfAzCZ5DJIM3dWnpodAOSlOVdEKcYqhfmH6yM=,tag:Z/c5QKvG9Xtl9EPxIgMq0w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
