k3s_token: ENC[AES256_GCM,data:/YKsK2vS,iv:1Xct7I2ZrcnRbQVNd25nUKDJzjrzkgboSpsH++aw8FA=,tag:nLfNSIm55xqw7sVlC/SMtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kjqhsyucjhuw6gazjrjqcuavay6pfgpr8fasltft99vzfdkjdsdsvfx4xv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaSs3YUJRUnpRSDVreGdG
            anBQZWRwa2FMNkY4M3hlUGw1dFNtQjNlb1RVCit3SUFZc2VaK3JIb0kvanFiMFdp
            RDVrOEZJQWJUOFQzdzRkbEJZQllxVkUKLS0tIDZCSHdwTFh3VTZCaUdJVm80akc2
            Myt1S1J1dm9CTXIxREsyaG1id0NlY1EKZfhQGv+FHAbC3g0Pi1KdpJeRn1u9aoQv
            muDu5ZDdRv6ounpuYt9EYqcOMvAP0IiiDxPPR6fHlQJTpByL1RIw2g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ff98yfdlxax5ymnlu9rdzermuyvg8jwq98z6h86tpj8ajlxw7upsq4k8a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1QS9BbnhDRVBzdGNTUG1C
            TjMrMzc2QVZuZkNaQ05Ma0lXRU1YbnNMVlJBCmdIMEVZSVk0WUNRdnozeXFuMmxs
            S2R4YjVUbGdHQW1RZExGY0daQ3VMMHMKLS0tIEk0VlVWT1JZTldmN1NGdHk1ZXVk
            SnVKOTdkcW02M3U4SC9aYWRKVHNDRW8K1LmAB+yw366/q0SV3jn9EOh6LW6KE/Mc
            kSd63e/4na46e7J3hC+WZDKaxVJ8TNqBgrTv9a4HPc1ky146cMRAkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-21T20:57:25Z"
    mac: ENC[AES256_GCM,data:Q/fUAZoVzdqIOogfCu17FAOxM4c4g9pny7lhuJ3L7rRGJpfaDUDdFabkfb9RMwlltFJe+qXAQLK73N/XLZnXL39xkCJocGYrr3gZbHQ5PtPjWkn29pEL7q9nbqBu9xaMiG71Bduil3d2h05tELnfGp/u4zHzrLEEQD8JFbfy5wc=,iv:o3+Lnr8Hm8NtSrjx6DPH/QHUkRvxQkbQpZ8vq2frxtg=,tag:XA6ont56hY5s+G/istaxBA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
